#ifndef TETRIS_CONSTANTS_H
#define TETRIS_CONSTANTS_H


const int32_t CNT_TETRIMINOS = 7;
const int32_t CNT_NEXT_PIECES = 3;
const int32_t MAX_LEVEL = 20;

const int32_t SCREEN_WIDTH_PIXELS = 400;
const int32_t SCREEN_HEIGHT_PIXELS = 300;
const int32_t SCREEN_PIXEL_SIZE = 2;
const int32_t TILE_PIXELS = 12;

const int32_t TABLE_WIDTH_TILES = 10;
const int32_t TABLE_HEIGHT_TILES = 20;
const int32_t EXTRA_HEIGHT_TILES = 6;
const size_t BOARD_SIZE = TABLE_WIDTH_TILES * (TABLE_HEIGHT_TILES + EXTRA_HEIGHT_TILES);

const int32_t TABLE_WIDTH_PIXELS = TABLE_WIDTH_TILES * TILE_PIXELS;
const int32_t TABLE_HEIGHT_PIXELS = TABLE_HEIGHT_TILES * TILE_PIXELS;
const int32_t TABLE_START_X = (SCREEN_WIDTH_PIXELS - TABLE_WIDTH_PIXELS) / 2;
const int32_t TABLE_START_Y = (SCREEN_HEIGHT_PIXELS - TABLE_HEIGHT_PIXELS) / 2;

const int32_t FADE_OUT_STEPS = 16;

#endif // TETRIS_CONSTANTS_H

